services:
  nlaundry_site:
    image: nginx:latest
    container_name: nlaundry_site
    restart: unless-stopped
    networks:
      - traefik_net
    volumes:
      - $VOLUMES_DIR/nlaundry_site/public:/usr/share/nginx/html:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nlaundry_site.entrypoints=websecure"
      - "traefik.http.routers.nlaundry_site.tls.certresolver=resolver"
      - "traefik.http.routers.nlaundry_site.rule=Host(`$DOMAINNAME`)"
      - "traefik.http.routers.nlaundry_site.service=nlaundry-site-nlaundry-site"

networks:
  traefik_net:
    name: $TRAEFIK_NET
    external: true
