## STATIC CONFIGURATION
log:
  level: INFO

api:
  insecure: true
  dashboard: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entrypoint:
          to: "websecure"
          scheme: "https"
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

certificatesResolvers:
  resolver:
    acme:
      email: "admin@nathanlaundry.com"
      storage: "/etc/traefik/acme/acme.json" # this has to be the file location INSIDE THE CONTAINER, NOT on the host.
      httpChallenge:
        entryPoint: "web"
      tlsChallenge: "true"
